######################################################################################################
# Orion configuration
######################################################################################################
#orion: 
  #security:
    #rest:
      #authenticated:
        #paths: /shipmentdata/v2/**
        
        
orion:
  build:
    version: 2018.11.1
  properties:
    type: local-properties
    version: 1.0 
  security:
    rest:
      authenticated:
        paths: /shipmentdata/v2/**        

oauth.server.url: https://websec-int.cable.comcast.com/as/token.oauth2
authServer:
  publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuyHtPtU4wlq70yhZ6RSvuhNSp3TqXaDu2jLnVtGasqV8Iybvgzlx6bWD4wbky9u7g5g8uX/HsCTTse/dhniAnvxWU5PW+jyVUSCN4UX98PSYH2C/QhLrJD6wzQ4CTJxJq7uhfZLkpgJJAl7vr8qLegsYzYg2LC5x/uu7e/QtJfSxmvpGDNyrj3rvWKkodghXWkYQ+qrv7k5vii20pRnnKsN6JfKCTNCVp0Sz5h49ko+x1buTe4dOYpqM067bDk1bgf2kI7MoqJ3e+p9yHgJs+K3BVOKUPPaLBtSMJokGxdyYwND8MltmvCuAmMYhGENuWQpwtca/JotojpPxHxn3rQIDAQAB-----END PUBLIC KEY-----
  scope: orion:orion-dev,orion:amdocs

# Dev Configuration
spring:
  profiles: dev
  application.name: shipmentdata-service
  datasource:
    username: 0^^wdevu$r
    password: ap@d4v$p
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://orisqldb-dt-1d.ula.comcast.net:3306/orionmw_ofs
    #initialize: true
    initialization-mode: always 
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      cache:
      user_query_cache: true
    dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true
    format_sql: false
    jdbc:
      fetch_size: 500
      batch_size: 500
    order_inserts: true
    order_updates: true 
      
        
eureka.client.enabled:  false

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    com.comcast.orion: DEBUG
  file: logs/shipmentdata-service.log
server:
  port: 9001
  

xsp:
  security:
    authServer:
      configs:
       - endpointPatterns: localhost,orion,data,orion-gateway
         username: orion_dev
         secret: c02af9ff99dc45019fcba878fc90cb10
         scopes: orion:orion-dev
  
  
hystrix: 
  command: 
    default: 
      circuitBreaker: 
        enabled: true
        errorThresholdPercentage: 55
        forceClosed: false
        forceOpen: false
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 100
      execution: 
        isolation: 
          semaphore: 
            maxConcurrentRequests: 100
          thread: 
            interruptOnCancel: false
            interruptOnTimeout: 1000
            timeoutInMilliseconds: 30000
      fallback: 
        enabled: true
        isolation: 
          semaphore: 
            maxConcurrentRequests: 100
        timeout: 
          enabled: true
      metrics: 
        healthSnapshot: 
          intervalInMilliseconds: 500
        rollingPercentile: 
          bucketSize: 100
          enabled: true
          numBuckets: 6
          timeInMilliseconds: 60000
        rollingStats: 
          numBuckets: 10
          timeInMilliseconds: 10000
      requestCache: 
        enabled: false
      requestLog: 
        enabled: false
    downstreamOperationHystrix: 
      circuitBreaker: 
        errorThresholdPercentage: 55
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 100
      execution: 
        isolation:
          thread: 
            timeoutInMilliseconds: 30000
      metrics: 
        healthSnapshot: 
          intervalInMilliseconds: 500
        rollingPercentile: 
          bucketSize: 100
          enabled: true
          numBuckets: 6
          timeInMilliseconds: 60000
        rollingStats: 
          numBuckets: 10
          timeInMilliseconds: 10000
      requestCache: 
        enabled: false
      requestLog: 
        enabled: false
  threadpool: 
    downstreamOperationHystrix: 
      allowMaximumSizeToDivergeFromCoreSize: false
      coreSize: 10
      keepAliveTimeMinutes: 1
      maxQueueSize: -1
      maximumSize: 10
      queueSizeRejectionThreshold: 5

devices:
  wanupgradesupport: Edgewater_Networks       