inherit: ../../../shared/config-server-properties-orion-int.yml
memory: 2048M
timeout: 600
host: shipmentdata-int
instances: 2
services:
- Orion-RabbitMQ
- app-dynamics-service
applications:
- name: shipmentdata-int
env: 
 JAVA_OPTS: -Dappdynamics.agent.applicationName=orion-int -Dappdynamics.agent.tierName=ORION -Dappdynamics.agent.nodeName=shipmentdata-int -Dappdynamics.http.proxyHost=proxy-appd-lower.sys.comcast.net -Dappdynamics.http.proxyPort=3128 -Dappdynamics.force.default.ssl.certificate.validation=false

